### ISSUE TITLE
Cottongut -> Blood recipe only uses 1 Cottongut

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pyalienlife#11]
Cottongut -> Blood in Slaughterhouse is 1 Cottongut -> 100 Blood. All other Cottongut slaughter recipes use 5 Cottonguts. This is only an issue after the 2nd upgrade tech (Therapeutic DNA transgenes).

![20200331174804_1](https://user-images.githubusercontent.com/22365274/77995847-3f179000-7378-11ea-97f5-3e0c7bd65737.jpg)

**Comment by pyanodon** [comment]
thx
