### ISSUE TITLE
Incorrect key used in locale.cfg

### ISSUE THREAD

**Issue by Squelch** [pyanodon/pyalienlife#12]
### Description:

Factorio attempts to reference "fuel-category-name" from the locale file. The current entry in locale.cfg is "[fuel-category]"

fuel-category.name shows "unknown key"

### Reproduction:

1. Start a fresh map with AlienLife 1.5.1 enabled on Factorio 0.18.17
2. Select any empty quickbar slot
3. Type any of the names from the list below into the search filter
4. Hold pointer over icon to read the name and description
```
[fuel-category]
food=Food
meat=Meat
drill=Drill heads
bio-container=Bio containers
```
From [locale.cfg](https://github.com/pyanodon/pyalienlife/blob/60d7c1125d609e9cc8baa61dc4f0af10cc06f38b/locale/en/locale.cfg#L1911)

### Result:

All of the fuel-category names show "Unknown key"
![alienlife-fuel-category](https://user-images.githubusercontent.com/48508/78729580-51726a80-7932-11ea-96f1-ebea4d0d66f3.PNG)

**Comment by Squelch** [comment]
The section name on Line 1911 of locale.cfg should be:

`[fuel-category-name]`

This corrects the problem and the names are then displayed correctly.

I can submit a pull request for this change if desired?

**Comment by pyanodon** [comment]
yes plz

**Comment by Squelch** [comment]
Cloning now on slow connection. Will be a few moments.
