### ISSUE TITLE
plastic-from-nothing recipe in 2.0.0

### ISSUE THREAD

**Issue by tux3** [pyanodon/pyalienlife#176]
This [https://github.com/pyanodon/pyalienlife/blob/931da25bf17a7df441bcc7908c92fd3d45da5e1f/prototypes/updates/pypetroleumhandling-updates.lua#L250-L262](plastic-from-nothing) recipe shows up for me in game.  
It makes plastic from just electricity, so I'm not sure it was intended to make it in in the release? =)

![snap-1069](https://user-images.githubusercontent.com/5155966/196039956-4094e609-f003-48fd-9fc1-c8eabba427bc.jpg)

I updated from a save I created just before 2.0.0, where I had a few early techs researched, so I'm not sure if this is a factor.

**Comment by kingarthur91** [comment]
Already aware. Already reported. Already fixed for the next update. 
Your the weakest link and have been voted off the island. Assuming you survive the sharks try again next time

**Comment by tux3** [comment]
Damn, I did search issues but didn't see it. Thanks, I'll take my chances with the sharks
