### ISSUE TITLE
Don't crash if tree.minable is nil

### ISSUE THREAD

**Issue by DarkShadow44** [pyanodon/pyalienlife#189]
It's inside `prototypes/recipes/sap/recipes-sap.lua`, inside the `for _, tree in pairs(data.raw.tree) do` loop.
There are already nil checks, but then it's accesses without checking:
`if tree.minable.results[1].amount >= 1 then`

**Comment by notnotmelon** [comment]
This is fixed for the next release. Thanks for the report.
