### ISSUE TITLE
crash on new game 

### ISSUE THREAD

**Issue by filipagh** [pyanodon/pyalienlife#193]
hi i got this crash report 

![image](https://user-images.githubusercontent.com/22474494/210920796-4b4d5a36-a451-416a-b935-43bdf7e1acf2.png)

tested on only pyanodons mods (all updated)
factorio 1.1.74  
linux 
![image](https://user-images.githubusercontent.com/22474494/210921478-15789715-8a90-4735-a7c0-2646327c87d9.png)

**Comment by notnotmelon** [comment]
Fixed!
