### ISSUE TITLE
migration error - indexed farm list - nil value

### ISSUE THREAD

**Issue by filipagh** [pyanodon/pyalienlife#194]
old save migration to new version 

![image](https://user-images.githubusercontent.com/22474494/210926159-0c3abc09-8893-4893-afae-d4d8dfd25ce7.png)

**Comment by dafandango** [comment]
Can be fixed by commenting out the second line in pyalienlife_2.0.8/migrations/2.0.7.lua, i.e. replacing

`	game.print('pYAL: Migrated ' .. #global.indexed_farm_list .. ' farm buildings')`

by

`--	game.print('pYAL: Migrated ' .. #global.indexed_farm_list .. ' farm buildings')`

**Comment by notnotmelon** [comment]
This was fixed in dev. Closing
