### ISSUE TITLE
duplicate energy source for fluid mining drill mk01

### ISSUE THREAD

**Issue by filipagh** [pyanodon/pyalienlife#196]
hello, i found out that fluid mining drill mk01 need multiple energy source is this intended ? 
it need coal gas (which nake sense)
but also need solid fuel 
![image](https://user-images.githubusercontent.com/22474494/211405493-0498900c-8a04-4516-a456-003dfc329e02.png)

i think only 1 (coal gas) should be needed

**Comment by notnotmelon** [comment]
This is intended. The coal gas is just the required mining fluid.
