### ISSUE TITLE
Pyanodon Codex doesn't check if recipes exist (T.U.R.D.)

### ISSUE THREAD

**Issue by 04Slash** [pyanodon/pyalienlife#204]
**Describe the bug**
The T.U.R.D. section of the Pyanodon Codex does not check if recipes are missing. If PyAL is installed and PyAE is not installed, the error in the screenshot below will happen.

**To Reproduce**
1. Download PyAL v2.1.0 or above
2. Remove PyAE (if already present)
3. Load game, create world
4. Open Pyanodon Codex and click T.U.R.D.
5. Receive error and get kicked to main menu

**Expected behavior**
The expected behavior is that the Codex should check if the recipe exists. Ideally, if it's possible, this should be done in a catch-all way as to not cause issues with mods that change recipe names, such as Omnipermute or Fluid Permutation, rather than looking for hardcoded recipe names.

**Screenshots**
![image](https://user-images.githubusercontent.com/57328541/228466102-77dbc60c-38b8-498b-9c40-a2c6a7395cf2.png)

**Additional context**
If compatibility with Omnipermute is considered, [a fix will have to be applied](https://github.com/Omnimods/Omnimods/commit/83265949c7f1118c8b6fbbc295cc1f3f9e1d29d4) for it to load with PyAL present since this update has yet to be released.

**Additional Info**
- Factorio Version: 1.1.78
- Minimal required mods to reproduce: PyAL v2.1.0+ (+ Dependencies)
- Savegame: N/A

**Comment by notnotmelon** [comment]
Fixed! See: https://github.com/pyanodon/pyalienlife/commit/2539ade39b3c77524b45a35bab91ddb60799ed40
