### ISSUE TITLE
TURD: typo in recipe name causes bug

### ISSUE THREAD

**Issue by ilit** [pyanodon/pyalienlife#205]
TURD open -> crash

```
1960.075 Error MainLoop.cpp:1288: Exception at tick 31878258: The mod Pyanodons Coal Processing (2.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event pycoalprocessing::on_gui_selection_state_changed (ID 60)
Error when running interface function pywiki_turd_page.create_turd_page: Unknown recipe name: denatured-seismite-2
stack traceback:
	[C]: in function '__newindex'
	__pyalienlife__/scripts/turd/turd.lua:146: in function <__pyalienlife__/scripts/turd/turd.lua:73>
stack traceback:
	[C]: in function 'call'
	__pycoalprocessing__/scripts/wiki/wiki.lua:161: in function 'open_page'
	__pycoalprocessing__/scripts/wiki/wiki.lua:170: in function 'handler'
	__stdlib__/stdlib/event/event.lua:342: in function 'pcall'
	__stdlib__/stdlib/event/event.lua:359: in function 'dispatch_event'
	__stdlib__/stdlib/event/event.lua:438: in function <__stdlib__/stdlib/event/event.lua:396>
```

PyCoal 2.1.0
Factorio 1.80

Probably typo in recipe name somewhere?
**denatured**-seismite
**denaturated**-seismite

I've seen this kind of typo in [https://mods.factorio.com/mod/pyalienlife/changelog](url)

Could not find if it was fixed or not.
Last TURD fixes commit contains nothing about _seismite_
[https://github.com/pyanodon/pyalienlife/commit/2539ade39b3c77524b45a35bab91ddb60799ed40](url)

**Comment by notnotmelon** [comment]
You are missing pY Alternative Energy. https://mods.factorio.com/mod/pyalternativeenergy

The crash without AE was fixed here: https://github.com/pyanodon/pyalienlife/commit/2539ade39b3c77524b45a35bab91ddb60799ed40z

Thanks for the report.
