### ISSUE TITLE
Speed modules work in alien buildings

### ISSUE THREAD

**Issue by kmod** [pyanodon/pyalienlife#24]
which lets you skip synthesizing your first plant/creature

I believe the problem is here:
https://github.com/pyanodon/pyalienlife/blob/c87fc83bc6ff1df6074bf5839b754bf99614e230/data-final-fixes.lua#L186
It looks like the `effectivityblacklist` function expects to be passed a list of crafting categories to blacklist, but instead it gets passed a list of recipe names, so I think it ends up not blacklisting anything.
(Also it's called "effectivityblacklist" but blacklists speed modules)

**Comment by oorzkws** [comment]
Resolved in dev.
