### ISSUE TITLE
duplicate dried meat recipe

### ISSUE THREAD

**Issue by ironchefpython** [pyanodon/pyalienlife#25]
With both high tech and alien life mod loaded, there appear to be two identical recipes for dried meat.

**Comment by oorzkws** [comment]
recipe names are `dried-meat` and `dried-meat-01`

The former is unlocked by tech `fuel-production`, the latter by `rendering`. Both share the same machines.

I'll leave this for after the AL tech tree reflow.

**Comment by oorzkws** [comment]
Dried meat was changed recently, resolving this.
