### ISSUE TITLE
cadaveric arum mark x missing recipe

### ISSUE THREAD

**Issue by JanEggers** [pyanodon/pyalienlife#26]
@kingarthur91 as requested in the discussion the savegames: i had to split it in rar and rename as zip so the upload is accepted

the issue i have is:

seeds require pulp => pulp requires plants => plants require seeds 

and I suppose there should be a recipe that give 0.5 % of mark ii seeds but instead the tec contains another blueprint for a plant mark ii

[py al.part01.rar.zip](https://github.com/pyanodon/pyalienlife/files/5504750/py.al.part01.rar.zip)
[py al.part02.rar.zip](https://github.com/pyanodon/pyalienlife/files/5504752/py.al.part02.rar.zip)
[py al.part03.rar.zip](https://github.com/pyanodon/pyalienlife/files/5504753/py.al.part03.rar.zip)

**Comment by JanEggers** [comment]
https://github.com/pyanodon/pyalienlife/blob/26ceb1676fc1f152e0e5f797458da549b9930bdc/prototypes/recipes/recipes-cadaveric.lua#L154

this is missing for me

**Comment by JanEggers** [comment]
@kingarthur91 are there any guides on how to debug factorio? i am really bottlenecking on sulfuric acid :)

**Comment by oorzkws** [comment]
Looks like this was since resolved in dev, or at least I don't see that loop happening anymore.
