### ISSUE TITLE
Cottongut "Temperature Spots" T.U.R.D increases speed

### ISSUE THREAD

**Issue by 04Slash** [pyanodon/pyalienlife#39]
Taking a look at the code, it would appear that `module_amount` is suppose to be `-8` which would line up with other buildings.

https://github.com/pyanodon/pyalienlife/blob/master/prototypes/upgrades/cottongut.lua#L78-L79
<details>
<summary>Picture of  cottongut issue</summary>
<br>

![](https://i.imgur.com/EUTD15A.png)

</details>

---

Similarly to Cottonguts, Fastwood Forestry, Sap, Seaweed, also has this issue.

https://github.com/pyanodon/pyalienlife/blob/master/prototypes/upgrades/fwf.lua#L45-L46
https://github.com/pyanodon/pyalienlife/blob/master/prototypes/upgrades/sap.lua#L111-L112
https://github.com/pyanodon/pyalienlife/blob/master/prototypes/upgrades/seaweed.lua#L77-L78

---

On the topic of TURD speed changes, the shown value doesn't give an accurate representation of the actual effect that the upgrade will have. I was surprised to see my Ulric manure production drop from 15/s to 1/s from -10% speed (so much so that I thought it was bugged). I'm not against how it's done but do think it could be displayed better because "-10% speed" shouldn't cause that much of a drop.

_~~Lastly, is there a way to reset the TURD bonuses? If you load a save with different mod configurations it allows you to select your TURD bonuses again. This results in stacking TURD bonuses. I didn't realize this was happening and would like to be able to get rid of the extra bonuses.~~_
Disregard, figured it out. For anyone wondering in the future, you can remove the effects by killing all the invisible beacons on the map. From here just grab the effects from the TURD menu again and everything should be fine. Command to kill: `/c for _, entity in ipairs(game.player.surface.find_entities_filtered{name="hidden-beacon"}) do entity.destroy() end`

**Comment by notnotmelon** [comment]
Fixed.
