### ISSUE TITLE
araq-filled-honeycomb recipe (series) is missing an actual name

### ISSUE THREAD

**Issue by hasezoey** [pyanodon/pyalienlife#40]
recipe series name is `araq-filled-honeycomb-*` (`*` is the number)

versions:
Factorio: 1.1.35
PyAlienLife: 1.12.4

![Screenshot from 2021-06-26 12-06-03](https://user-images.githubusercontent.com/10911626/123509643-ec11b300-d676-11eb-917b-777422289312.png)

---

Edit:
i also just noticed the series `araq-filled-comb-*` is also missing an name

**Comment by hasezoey** [comment]
update: in current version (1.12.4), these still have no actual name

**Comment by oorzkws** [comment]
![image](https://user-images.githubusercontent.com/65210810/151644611-957691e0-f80d-42f6-882e-321a9a77b0c7.png)
looks like this was since resolved

**Comment by hasezoey** [comment]
>  looks like this was since resolved

i am on alienlife 1.12.4 (current latest available version on mods.factorio), i am still seeing my initial problem:
![also_still_there](https://user-images.githubusercontent.com/10911626/151648862-def6e608-8422-499d-9bdd-408a147a49b7.png)
