### ISSUE TITLE
TURD bonus for research center do not affect normal science packs

### ISSUE THREAD

**Issue by Nagapito** [pyanodon/pyalienlife#42]
The multiple TURD bonus do not have any effect on normal non-Alien Life science recipes, only affecting Alien Life recipes.

The reason for this is that non-alien life science pack recipes only get the category research in the data-final-fixes.lua but the recipes assigned to these bonus are set in the data-updates.lua, that is, before these reipes have the research category

**Comment by notnotmelon** [comment]
Fixed.
