### ISSUE TITLE
Crash site assembler/juicer can't be repaired by hand

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pyalienlife#66]
Sometimes the mentioned entities are damaged in the fire/explosions of the crashed ship at the very beginning.
It's not possible to repair them using repair packs. I could repair them by building a roboport and use construction bots to repair them, though.

Nothing big, just triggers my OCD. And I get that warning that I can't get rid of until I build my first bots.
<img width="175" alt="image" src="https://user-images.githubusercontent.com/22458042/150589312-54c1dffc-2d44-47d0-b488-f21fbae72666.png">

Perhaps the solution should be to move the buildings further away from the fire to not damage them in the first place.

**Comment by oorzkws** [comment]
partially addressed: 4dcebeef

**Comment by SWeini** [comment]
fire resistance is also a solution to the crash site fire. if someone plays with biters or shoots it deliberately they know what they are doing. issue can be closed unless you want to improve this further.

**Comment by SWeini** [comment]
Adding 'player-creation' flag would allow for repairing
