### ISSUE TITLE
Research center mk progression weird

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pyalienlife#67]
Research centers have these stats for mk 1/2/3/4:
crafting speed: 0.5/0.75/1.0/1.25

the normal progression is
crafting speed: 1/2/3/4

This inconsistency makes it impossible to upgrade the whole factory to a new mk level at once without destroying ratios. Especially with most other crafting speeds set to 1/2/3/4 players might not be aware that this is a problem and be bottlenecked by the slower research centers.

**Comment by pyamods** [comment]
fixed
