### ISSUE TITLE
Upgrading buildings should be easier

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pyalienlife#68]
Is it by design, that Py buildings don't have no [next_upgrade](https://wiki.factorio.com/Prototype/Entity#next_upgrade) defined? It's not even possible to put all building upgrade paths into a single upgrade planner because these only support up to 24 upgrades. This makes upgrading whole builds more cumbersome than it should be.

**Comment by oorzkws** [comment]
I gave it some work programmatically, but I'm not 100% pleased with the efficiency of this method. It'll probably be better for me to individually modify each prototype file.
![image](https://user-images.githubusercontent.com/65210810/150678352-e42e996b-5138-4729-8c02-d85b0197f4a1.png)

**Comment by oorzkws** [comment]
Resolved (just PyAl for now)
