### ISSUE TITLE
Crash when opening pY wiki

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pyalienlife#69]
Click on the icon in the upper left corner. Some problem with the data_puller interface that I can only find in pyalienlife/old-control.lua which is probably not used anymore.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/22458042/150570530-b420c823-313e-40e3-ada9-a5a8c2e8c431.png">

**Comment by oorzkws** [comment]
known, wiki is WIP

**Comment by oorzkws** [comment]
Moved to frequent issues under pyanodon/pybugreports
