### ISSUE TITLE
Bioreserve resource has wrong icon/name in map generator settings

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pyalienlife#70]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/22458042/150570772-0fc9d20c-4b00-47c7-9383-652a4234dd1b.png">

The image should not be the bio containers but instead the native flora. Probably also makes sense to rename the resource to "Native Flora", here and in the map itself.

<img width="164" alt="image" src="https://user-images.githubusercontent.com/22458042/150571173-251b5484-456c-492e-8624-06b20435c58b.png">

**Comment by oorzkws** [comment]
This has since been resolved.
