### ISSUE TITLE
Balance needed for crashed ship juicer

### ISSUE THREAD

**Issue by SWeini** [pyanodon/pyalienlife#71]
Given the current recipes and buildings the situation looks as follows:
- The juicer is the only way to create latex which you need for red science
- The single juicer has 0.1 crafting speed
- With that single juicer you can make 0.9/minute red science
- The pulp mill replacement needs ~1.17k red science
- You are limited to 0.9 spm for 21.66 hours until you can scale up your production
- And there is nothing you can do about it (except mine native flora and chop some wood which you also need)

**Comment by oorzkws** [comment]
resolved; 8328efd
